//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpresosAlvarez.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contribuyentes
    {
        public int id_contribuyente { get; set; }
        public string nombre { get; set; }
        public string numero_factura { get; set; }
        public Nullable<int> tipo_factura { get; set; }
        public string num_complemento { get; set; }
    }
}
