//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpresosAlvarez.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorteDiario
    {
        public int id_corte_diario { get; set; }
        public string numero { get; set; }
        public string cliente { get; set; }
        public string contribuyente { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<double> total { get; set; }
        public string referencia { get; set; }
        public Nullable<int> id_entrega { get; set; }
        public string entrega { get; set; }
        public string observaciones { get; set; }
        public string tipo { get; set; }
        public string fecha_pago { get; set; }
        public string aplicado { get; set; }
        public string fecha_aplicado { get; set; }
        public Nullable<int> id_factura { get; set; }
        public Nullable<int> id_nota { get; set; }
    }
}
