//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpresosAlvarez.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int id_detallefactura { get; set; }
        public int id_factura { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> importe { get; set; }
        public Nullable<double> precio_unitario { get; set; }
        public string clave_servicio { get; set; }
        public string unidad { get; set; }
        public Nullable<int> id_articulo { get; set; }
    }
}
