//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpresosAlvarez.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int id_factura { get; set; }
        public int id_cliente { get; set; }
        public int id_contribuyente { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<double> total { get; set; }
        public string pagada { get; set; }
        public string estado { get; set; }
        public string fecha { get; set; }
        public string numero { get; set; }
        public string razon_cancelado { get; set; }
        public string amparada_por { get; set; }
        public string usuario { get; set; }
    }
}
