//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpresosAlvarez.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordenes()
        {
            this.Bitacora = new HashSet<Bitacora>();
            this.Disenos = new HashSet<Disenos>();
            this.Entrega = new HashSet<Entrega>();
            this.Terminado = new HashSet<Terminado>();
        }
    
        public int id_orden { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public double numero { get; set; }
        public string telefono { get; set; }
        public string solicitante { get; set; }
        public string fecha_solicita { get; set; }
        public string quien_recibio { get; set; }
        public string inicio_diseno { get; set; }
        public string nombre_trabajo { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string color_tintas { get; set; }
        public string tipo_papel { get; set; }
        public string con_folio { get; set; }
        public string del_numero { get; set; }
        public string al_numero { get; set; }
        public string tamano { get; set; }
        public string otros_1 { get; set; }
        public string otros_2 { get; set; }
        public string copia_1 { get; set; }
        public string copia_2 { get; set; }
        public string copia_3 { get; set; }
        public string copia_4 { get; set; }
        public string otros_3 { get; set; }
        public string otros_4 { get; set; }
        public string pegado { get; set; }
        public string engrapado { get; set; }
        public string perforacion { get; set; }
        public string rojo { get; set; }
        public string blanco { get; set; }
        public string especificaciones { get; set; }
        public string estado { get; set; }
        public string tipo { get; set; }
        public Nullable<double> total { get; set; }
        public string muestra { get; set; }
        public string fecha_muestra { get; set; }
        public string prioridad { get; set; }
        public Nullable<double> anticipo { get; set; }
        public string fecha_entregado { get; set; }
        public string pagado { get; set; }
        public string inicio_impresion { get; set; }
        public string inicio_terminado { get; set; }
        public string inicio_por_entregar { get; set; }
        public Nullable<double> costo_anterior { get; set; }
        public string autorizado { get; set; }
        public string hora_solicita { get; set; }
        public string ruta { get; set; }
        public string orden_anterior { get; set; }
        public string fecha_negativo { get; set; }
        public string tipo_maquina { get; set; }
        public string tipo_orden { get; set; }
        public string lona_medida { get; set; }
        public string lona_normal { get; set; }
        public string lona_traslucida { get; set; }
        public string lona_impresion_uv { get; set; }
        public string lona_impresion_ecosolvente { get; set; }
        public string lona_acabado_byo { get; set; }
        public string lona_acabado_bastilla { get; set; }
        public string lona_acabado_sobrante { get; set; }
        public string lona_acabado_bolsa { get; set; }
        public string lona_acabado_otro { get; set; }
        public string lona_acabado_observaciones { get; set; }
        public string vinil_medida { get; set; }
        public string vinil_tipo_brillante { get; set; }
        public string vinil_tipo_mate { get; set; }
        public string vinil_impresion_uv { get; set; }
        public string vinil_impresion_ecosolvente { get; set; }
        public string vinil_econo { get; set; }
        public string vinil_ecogris { get; set; }
        public string vinil_alta { get; set; }
        public string vinil_micro { get; set; }
        public string vinil_trans { get; set; }
        public string vinil_est_blanco { get; set; }
        public string vinil_est_trans { get; set; }
        public string vinil_reflejante { get; set; }
        public string vinil_observaciones { get; set; }
        public string otro_material { get; set; }
        public string envio_a { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bitacora> Bitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disenos> Disenos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrega> Entrega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terminado> Terminado { get; set; }
    }
}
