//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpresosAlvarez.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int id_pago { get; set; }
        public int id_factura { get; set; }
        public string tipo { get; set; }
        public double cantidad { get; set; }
        public string fecha { get; set; }
        public string numero_cheque { get; set; }
        public string banco { get; set; }
        public string numero_recibo { get; set; }
        public string notas { get; set; }
    }
}
