//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpresosAlvarez.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcialidades
    {
        public int id_parcialidad { get; set; }
        public Nullable<int> id_factura { get; set; }
        public string xml { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> anterior { get; set; }
        public Nullable<double> pagado { get; set; }
        public Nullable<double> insoluto { get; set; }
        public Nullable<int> parcialidad { get; set; }
    }
}
