//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpresosAlvarez.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidasInventario
    {
        public int id_salida { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> presupuesto { get; set; }
        public string factura { get; set; }
        public string orden_trabajo { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<int> id_insumo { get; set; }
        public string descripcion { get; set; }
        public string nota { get; set; }
    }
}
