//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpresosAlvarez.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaDirecta
    {
        public int id_venta_directa { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string fecha { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public string notas { get; set; }
        public string estado { get; set; }
        public Nullable<double> total { get; set; }
    }
}
