//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpresosAlvarez.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://v33.facturacfdi.mx:80/WSForcogsaService")]
        public string ImpresosAlvarez_mx_facturacfdi_v33_WSForcogsaService {
            get {
                return ((string)(this["ImpresosAlvarez_mx_facturacfdi_v33_WSForcogsaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://v33.facturacfdi.mx:80/WSCancelacionService")]
        public string ImpresosAlvarez_mx_facturacfdi_v331_WSCancelacionService {
            get {
                return ((string)(this["ImpresosAlvarez_mx_facturacfdi_v331_WSCancelacionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://v33.facturacfdi.mx:80/WSCancelacion40Service")]
        public string ImpresosAlvarez_mx_facturacfdi_v40_WSCancelacion40Service {
            get {
                return ((string)(this["ImpresosAlvarez_mx_facturacfdi_v40_WSCancelacion40Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dev33.facturacfdi.mx:80/WSForcogsaService")]
        public string ImpresosAlvarez_mx_facturacfdi_dev33_WSForcogsaService {
            get {
                return ((string)(this["ImpresosAlvarez_mx_facturacfdi_dev33_WSForcogsaService"]));
            }
        }
    }
}
