//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ImpresosAlvarez.mx.facturacfdi.v331 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSCancelacionPortBinding", Namespace="http://wservicios/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AcuseAceptacionRechazo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AcusePeticionesPendientes))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsultaRelacionados))]
    public partial class WSCancelacionService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Cancelacion_2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Cancelacion_1OperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarEstatusCFDI_1OperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarEstatusCFDI_2OperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCFDIRelacionado_1OperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCFDIRelacionado_2OperationCompleted;
        
        private System.Threading.SendOrPostCallback BuzonPeticionesCancelacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback AceptarRechazarSolicitudCancelacion_1OperationCompleted;
        
        private System.Threading.SendOrPostCallback AceptarRechazarSolicitudCancelacion_2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSCancelacionService() {
            this.Url = global::ImpresosAlvarez.Properties.Settings.Default.ImpresosAlvarez_mx_facturacfdi_v331_WSCancelacionService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Cancelacion_2CompletedEventHandler Cancelacion_2Completed;
        
        /// <remarks/>
        public event Cancelacion_1CompletedEventHandler Cancelacion_1Completed;
        
        /// <remarks/>
        public event ConsultarEstatusCFDI_1CompletedEventHandler ConsultarEstatusCFDI_1Completed;
        
        /// <remarks/>
        public event ConsultarEstatusCFDI_2CompletedEventHandler ConsultarEstatusCFDI_2Completed;
        
        /// <remarks/>
        public event ConsultarCFDIRelacionado_1CompletedEventHandler ConsultarCFDIRelacionado_1Completed;
        
        /// <remarks/>
        public event ConsultarCFDIRelacionado_2CompletedEventHandler ConsultarCFDIRelacionado_2Completed;
        
        /// <remarks/>
        public event BuzonPeticionesCancelacionCompletedEventHandler BuzonPeticionesCancelacionCompleted;
        
        /// <remarks/>
        public event AceptarRechazarSolicitudCancelacion_1CompletedEventHandler AceptarRechazarSolicitudCancelacion_1Completed;
        
        /// <remarks/>
        public event AceptarRechazarSolicitudCancelacion_2CompletedEventHandler AceptarRechazarSolicitudCancelacion_2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wservicios/", ResponseNamespace="http://wservicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsCancelacionResponse Cancelacion_2([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fecha, [System.Xml.Serialization.XmlElementAttribute("folios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] folios, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] SignatureType signatureType, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] accesos accesos) {
            object[] results = this.Invoke("Cancelacion_2", new object[] {
                        rfcEmisor,
                        fecha,
                        folios,
                        signatureType,
                        accesos});
            return ((wsCancelacionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void Cancelacion_2Async(string rfcEmisor, string fecha, string[] folios, SignatureType signatureType, accesos accesos) {
            this.Cancelacion_2Async(rfcEmisor, fecha, folios, signatureType, accesos, null);
        }
        
        /// <remarks/>
        public void Cancelacion_2Async(string rfcEmisor, string fecha, string[] folios, SignatureType signatureType, accesos accesos, object userState) {
            if ((this.Cancelacion_2OperationCompleted == null)) {
                this.Cancelacion_2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelacion_2OperationCompleted);
            }
            this.InvokeAsync("Cancelacion_2", new object[] {
                        rfcEmisor,
                        fecha,
                        folios,
                        signatureType,
                        accesos}, this.Cancelacion_2OperationCompleted, userState);
        }
        
        private void OnCancelacion_2OperationCompleted(object arg) {
            if ((this.Cancelacion_2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Cancelacion_2Completed(this, new Cancelacion_2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wservicios/", ResponseNamespace="http://wservicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsCancelacionResponse Cancelacion_1([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fecha, [System.Xml.Serialization.XmlElementAttribute("folios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] folios, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] publicKey, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] privateKey, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] accesos accesos) {
            object[] results = this.Invoke("Cancelacion_1", new object[] {
                        rfcEmisor,
                        fecha,
                        folios,
                        publicKey,
                        privateKey,
                        password,
                        accesos});
            return ((wsCancelacionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void Cancelacion_1Async(string rfcEmisor, string fecha, string[] folios, byte[] publicKey, byte[] privateKey, string password, accesos accesos) {
            this.Cancelacion_1Async(rfcEmisor, fecha, folios, publicKey, privateKey, password, accesos, null);
        }
        
        /// <remarks/>
        public void Cancelacion_1Async(string rfcEmisor, string fecha, string[] folios, byte[] publicKey, byte[] privateKey, string password, accesos accesos, object userState) {
            if ((this.Cancelacion_1OperationCompleted == null)) {
                this.Cancelacion_1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelacion_1OperationCompleted);
            }
            this.InvokeAsync("Cancelacion_1", new object[] {
                        rfcEmisor,
                        fecha,
                        folios,
                        publicKey,
                        privateKey,
                        password,
                        accesos}, this.Cancelacion_1OperationCompleted, userState);
        }
        
        private void OnCancelacion_1OperationCompleted(object arg) {
            if ((this.Cancelacion_1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Cancelacion_1Completed(this, new Cancelacion_1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wservicios/", ResponseNamespace="http://wservicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsConsultarEstatusCFDIResponse ConsultarEstatusCFDI_1([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlCFDI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] accesos accesos) {
            object[] results = this.Invoke("ConsultarEstatusCFDI_1", new object[] {
                        xmlCFDI,
                        accesos});
            return ((wsConsultarEstatusCFDIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarEstatusCFDI_1Async(string xmlCFDI, accesos accesos) {
            this.ConsultarEstatusCFDI_1Async(xmlCFDI, accesos, null);
        }
        
        /// <remarks/>
        public void ConsultarEstatusCFDI_1Async(string xmlCFDI, accesos accesos, object userState) {
            if ((this.ConsultarEstatusCFDI_1OperationCompleted == null)) {
                this.ConsultarEstatusCFDI_1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarEstatusCFDI_1OperationCompleted);
            }
            this.InvokeAsync("ConsultarEstatusCFDI_1", new object[] {
                        xmlCFDI,
                        accesos}, this.ConsultarEstatusCFDI_1OperationCompleted, userState);
        }
        
        private void OnConsultarEstatusCFDI_1OperationCompleted(object arg) {
            if ((this.ConsultarEstatusCFDI_1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarEstatusCFDI_1Completed(this, new ConsultarEstatusCFDI_1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wservicios/", ResponseNamespace="http://wservicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsConsultarEstatusCFDIResponse ConsultarEstatusCFDI_2([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string totalCFDI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uuid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string selloCFDI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] accesos accesos) {
            object[] results = this.Invoke("ConsultarEstatusCFDI_2", new object[] {
                        rfcEmisor,
                        rfcReceptor,
                        totalCFDI,
                        uuid,
                        selloCFDI,
                        accesos});
            return ((wsConsultarEstatusCFDIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarEstatusCFDI_2Async(string rfcEmisor, string rfcReceptor, string totalCFDI, string uuid, string selloCFDI, accesos accesos) {
            this.ConsultarEstatusCFDI_2Async(rfcEmisor, rfcReceptor, totalCFDI, uuid, selloCFDI, accesos, null);
        }
        
        /// <remarks/>
        public void ConsultarEstatusCFDI_2Async(string rfcEmisor, string rfcReceptor, string totalCFDI, string uuid, string selloCFDI, accesos accesos, object userState) {
            if ((this.ConsultarEstatusCFDI_2OperationCompleted == null)) {
                this.ConsultarEstatusCFDI_2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarEstatusCFDI_2OperationCompleted);
            }
            this.InvokeAsync("ConsultarEstatusCFDI_2", new object[] {
                        rfcEmisor,
                        rfcReceptor,
                        totalCFDI,
                        uuid,
                        selloCFDI,
                        accesos}, this.ConsultarEstatusCFDI_2OperationCompleted, userState);
        }
        
        private void OnConsultarEstatusCFDI_2OperationCompleted(object arg) {
            if ((this.ConsultarEstatusCFDI_2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarEstatusCFDI_2Completed(this, new ConsultarEstatusCFDI_2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wservicios/", ResponseNamespace="http://wservicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsConsultarCFDIRelacionadoResponse ConsultarCFDIRelacionado_1([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uuid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] publicKey, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] privateKey, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] accesos accesos) {
            object[] results = this.Invoke("ConsultarCFDIRelacionado_1", new object[] {
                        rfcEmisor,
                        rfcReceptor,
                        uuid,
                        publicKey,
                        privateKey,
                        password,
                        accesos});
            return ((wsConsultarCFDIRelacionadoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCFDIRelacionado_1Async(string rfcEmisor, string rfcReceptor, string uuid, byte[] publicKey, byte[] privateKey, string password, accesos accesos) {
            this.ConsultarCFDIRelacionado_1Async(rfcEmisor, rfcReceptor, uuid, publicKey, privateKey, password, accesos, null);
        }
        
        /// <remarks/>
        public void ConsultarCFDIRelacionado_1Async(string rfcEmisor, string rfcReceptor, string uuid, byte[] publicKey, byte[] privateKey, string password, accesos accesos, object userState) {
            if ((this.ConsultarCFDIRelacionado_1OperationCompleted == null)) {
                this.ConsultarCFDIRelacionado_1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCFDIRelacionado_1OperationCompleted);
            }
            this.InvokeAsync("ConsultarCFDIRelacionado_1", new object[] {
                        rfcEmisor,
                        rfcReceptor,
                        uuid,
                        publicKey,
                        privateKey,
                        password,
                        accesos}, this.ConsultarCFDIRelacionado_1OperationCompleted, userState);
        }
        
        private void OnConsultarCFDIRelacionado_1OperationCompleted(object arg) {
            if ((this.ConsultarCFDIRelacionado_1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCFDIRelacionado_1Completed(this, new ConsultarCFDIRelacionado_1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wservicios/", ResponseNamespace="http://wservicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsConsultarCFDIRelacionadoResponse ConsultarCFDIRelacionado_2([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uuid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] SignatureType signatureType, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] accesos accesos) {
            object[] results = this.Invoke("ConsultarCFDIRelacionado_2", new object[] {
                        rfcEmisor,
                        rfcReceptor,
                        uuid,
                        signatureType,
                        accesos});
            return ((wsConsultarCFDIRelacionadoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCFDIRelacionado_2Async(string rfcEmisor, string rfcReceptor, string uuid, SignatureType signatureType, accesos accesos) {
            this.ConsultarCFDIRelacionado_2Async(rfcEmisor, rfcReceptor, uuid, signatureType, accesos, null);
        }
        
        /// <remarks/>
        public void ConsultarCFDIRelacionado_2Async(string rfcEmisor, string rfcReceptor, string uuid, SignatureType signatureType, accesos accesos, object userState) {
            if ((this.ConsultarCFDIRelacionado_2OperationCompleted == null)) {
                this.ConsultarCFDIRelacionado_2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCFDIRelacionado_2OperationCompleted);
            }
            this.InvokeAsync("ConsultarCFDIRelacionado_2", new object[] {
                        rfcEmisor,
                        rfcReceptor,
                        uuid,
                        signatureType,
                        accesos}, this.ConsultarCFDIRelacionado_2OperationCompleted, userState);
        }
        
        private void OnConsultarCFDIRelacionado_2OperationCompleted(object arg) {
            if ((this.ConsultarCFDIRelacionado_2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCFDIRelacionado_2Completed(this, new ConsultarCFDIRelacionado_2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wservicios/", ResponseNamespace="http://wservicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsBuzonPeticionesCancelacionResponse BuzonPeticionesCancelacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] accesos accesos) {
            object[] results = this.Invoke("BuzonPeticionesCancelacion", new object[] {
                        rfcReceptor,
                        accesos});
            return ((wsBuzonPeticionesCancelacionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void BuzonPeticionesCancelacionAsync(string rfcReceptor, accesos accesos) {
            this.BuzonPeticionesCancelacionAsync(rfcReceptor, accesos, null);
        }
        
        /// <remarks/>
        public void BuzonPeticionesCancelacionAsync(string rfcReceptor, accesos accesos, object userState) {
            if ((this.BuzonPeticionesCancelacionOperationCompleted == null)) {
                this.BuzonPeticionesCancelacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuzonPeticionesCancelacionOperationCompleted);
            }
            this.InvokeAsync("BuzonPeticionesCancelacion", new object[] {
                        rfcReceptor,
                        accesos}, this.BuzonPeticionesCancelacionOperationCompleted, userState);
        }
        
        private void OnBuzonPeticionesCancelacionOperationCompleted(object arg) {
            if ((this.BuzonPeticionesCancelacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuzonPeticionesCancelacionCompleted(this, new BuzonPeticionesCancelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wservicios/", ResponseNamespace="http://wservicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsSolicitudAceptacionRechazoResponse AceptarRechazarSolicitudCancelacion_1([System.Xml.Serialization.XmlElementAttribute("folios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] wsFolioSolicitud[] folios, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fecha, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] publicKey, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] privateKey, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] accesos accesos) {
            object[] results = this.Invoke("AceptarRechazarSolicitudCancelacion_1", new object[] {
                        folios,
                        fecha,
                        rfcReceptor,
                        publicKey,
                        privateKey,
                        password,
                        accesos});
            return ((wsSolicitudAceptacionRechazoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AceptarRechazarSolicitudCancelacion_1Async(wsFolioSolicitud[] folios, string fecha, string rfcReceptor, byte[] publicKey, byte[] privateKey, string password, accesos accesos) {
            this.AceptarRechazarSolicitudCancelacion_1Async(folios, fecha, rfcReceptor, publicKey, privateKey, password, accesos, null);
        }
        
        /// <remarks/>
        public void AceptarRechazarSolicitudCancelacion_1Async(wsFolioSolicitud[] folios, string fecha, string rfcReceptor, byte[] publicKey, byte[] privateKey, string password, accesos accesos, object userState) {
            if ((this.AceptarRechazarSolicitudCancelacion_1OperationCompleted == null)) {
                this.AceptarRechazarSolicitudCancelacion_1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnAceptarRechazarSolicitudCancelacion_1OperationCompleted);
            }
            this.InvokeAsync("AceptarRechazarSolicitudCancelacion_1", new object[] {
                        folios,
                        fecha,
                        rfcReceptor,
                        publicKey,
                        privateKey,
                        password,
                        accesos}, this.AceptarRechazarSolicitudCancelacion_1OperationCompleted, userState);
        }
        
        private void OnAceptarRechazarSolicitudCancelacion_1OperationCompleted(object arg) {
            if ((this.AceptarRechazarSolicitudCancelacion_1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AceptarRechazarSolicitudCancelacion_1Completed(this, new AceptarRechazarSolicitudCancelacion_1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wservicios/", ResponseNamespace="http://wservicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsSolicitudAceptacionRechazoResponse AceptarRechazarSolicitudCancelacion_2([System.Xml.Serialization.XmlElementAttribute("folios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] wsFolioSolicitud[] folios, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fecha, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] SignatureType signatureType, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] accesos accesos) {
            object[] results = this.Invoke("AceptarRechazarSolicitudCancelacion_2", new object[] {
                        folios,
                        fecha,
                        rfcReceptor,
                        signatureType,
                        accesos});
            return ((wsSolicitudAceptacionRechazoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AceptarRechazarSolicitudCancelacion_2Async(wsFolioSolicitud[] folios, string fecha, string rfcReceptor, SignatureType signatureType, accesos accesos) {
            this.AceptarRechazarSolicitudCancelacion_2Async(folios, fecha, rfcReceptor, signatureType, accesos, null);
        }
        
        /// <remarks/>
        public void AceptarRechazarSolicitudCancelacion_2Async(wsFolioSolicitud[] folios, string fecha, string rfcReceptor, SignatureType signatureType, accesos accesos, object userState) {
            if ((this.AceptarRechazarSolicitudCancelacion_2OperationCompleted == null)) {
                this.AceptarRechazarSolicitudCancelacion_2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnAceptarRechazarSolicitudCancelacion_2OperationCompleted);
            }
            this.InvokeAsync("AceptarRechazarSolicitudCancelacion_2", new object[] {
                        folios,
                        fecha,
                        rfcReceptor,
                        signatureType,
                        accesos}, this.AceptarRechazarSolicitudCancelacion_2OperationCompleted, userState);
        }
        
        private void OnAceptarRechazarSolicitudCancelacion_2OperationCompleted(object arg) {
            if ((this.AceptarRechazarSolicitudCancelacion_2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AceptarRechazarSolicitudCancelacion_2Completed(this, new AceptarRechazarSolicitudCancelacion_2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureType {
        
        private SignedInfoType signedInfoField;
        
        private byte[] signatureValueField;
        
        private KeyInfoType keyInfoField;
        
        private ObjectType[] objectField;
        
        private string idField;
        
        /// <remarks/>
        public SignedInfoType SignedInfo {
            get {
                return this.signedInfoField;
            }
            set {
                this.signedInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
            }
        }
        
        /// <remarks/>
        public KeyInfoType KeyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Object")]
        public ObjectType[] Object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoType {
        
        private CanonicalizationMethodType canonicalizationMethodField;
        
        private SignatureMethodType signatureMethodField;
        
        private ReferenceType referenceField;
        
        private string idField;
        
        /// <remarks/>
        public CanonicalizationMethodType CanonicalizationMethod {
            get {
                return this.canonicalizationMethodField;
            }
            set {
                this.canonicalizationMethodField = value;
            }
        }
        
        /// <remarks/>
        public SignatureMethodType SignatureMethod {
            get {
                return this.signatureMethodField;
            }
            set {
                this.signatureMethodField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceType Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class CanonicalizationMethodType {
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsSolicitudAceptacionRechazoResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cancelacfd.sat.gob.mx")]
    public partial class AcuseAceptacionRechazo {
        
        private AcuseAceptacionRechazoFolios[] foliosField;
        
        private SignatureType signatureField;
        
        private string rfcReceptorField;
        
        private string rfcPacField;
        
        private string codEstatusField;
        
        private System.DateTime fechaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folios")]
        public AcuseAceptacionRechazoFolios[] Folios {
            get {
                return this.foliosField;
            }
            set {
                this.foliosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public SignatureType Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RfcReceptor {
            get {
                return this.rfcReceptorField;
            }
            set {
                this.rfcReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RfcPac {
            get {
                return this.rfcPacField;
            }
            set {
                this.rfcPacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodEstatus {
            get {
                return this.codEstatusField;
            }
            set {
                this.codEstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cancelacfd.sat.gob.mx")]
    public partial class AcuseAceptacionRechazoFolios {
        
        private string uUIDField;
        
        private string estatusUUIDField;
        
        private string respuestaField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string EstatusUUID {
            get {
                return this.estatusUUIDField;
            }
            set {
                this.estatusUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wservicios/")]
    public partial class wsSolicitudAceptacionRechazoResponse : AcuseAceptacionRechazo {
        
        private string mensajeField;
        
        private wsSolicitudAceptacionRechazoResponseFolios[] foliosField;
        
        private string acuseField;
        
        private string rfcReceptorField;
        
        private string rfcPacField;
        
        private string codEstatusField;
        
        private string fechaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("folios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wsSolicitudAceptacionRechazoResponseFolios[] folios {
            get {
                return this.foliosField;
            }
            set {
                this.foliosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acuse {
            get {
                return this.acuseField;
            }
            set {
                this.acuseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfcReceptor {
            get {
                return this.rfcReceptorField;
            }
            set {
                this.rfcReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfcPac {
            get {
                return this.rfcPacField;
            }
            set {
                this.rfcPacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codEstatus {
            get {
                return this.codEstatusField;
            }
            set {
                this.codEstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://wservicios/")]
    public partial class wsSolicitudAceptacionRechazoResponseFolios {
        
        private string uUIDField;
        
        private string estatusUUIDField;
        
        private string respuestaField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string EstatusUUID {
            get {
                return this.estatusUUIDField;
            }
            set {
                this.estatusUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wservicios/")]
    public partial class wsFolioSolicitud {
        
        private string respuestaField;
        
        private string uUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsBuzonPeticionesCancelacionResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cancelacfd.sat.gob.mx")]
    public partial class AcusePeticionesPendientes {
        
        private string[] uUIDField;
        
        private string codEstatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUID")]
        public string[] UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodEstatus {
            get {
                return this.codEstatusField;
            }
            set {
                this.codEstatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wservicios/")]
    public partial class wsBuzonPeticionesCancelacionResponse : AcusePeticionesPendientes {
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cancelacfd.sat.gob.mx")]
    public partial class UuidRelacionado {
        
        private string uuidField;
        
        private string rfcEmisorField;
        
        private string rfcReceptorField;
        
        /// <remarks/>
        public string Uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        public string RfcEmisor {
            get {
                return this.rfcEmisorField;
            }
            set {
                this.rfcEmisorField = value;
            }
        }
        
        /// <remarks/>
        public string RfcReceptor {
            get {
                return this.rfcReceptorField;
            }
            set {
                this.rfcReceptorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cancelacfd.sat.gob.mx")]
    public partial class UuidPadre {
        
        private string uuidField;
        
        private string rfcEmisorField;
        
        private string rfcReceptorField;
        
        /// <remarks/>
        public string Uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        public string RfcEmisor {
            get {
                return this.rfcEmisorField;
            }
            set {
                this.rfcEmisorField = value;
            }
        }
        
        /// <remarks/>
        public string RfcReceptor {
            get {
                return this.rfcReceptorField;
            }
            set {
                this.rfcReceptorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsConsultarCFDIRelacionadoResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cancelacfd.sat.gob.mx")]
    public partial class ConsultaRelacionados {
        
        private string uuidConsultadoField;
        
        private string resultadoField;
        
        private UuidPadre[] uuidsRelacionadosPadresField;
        
        private UuidRelacionado[] uuidsRelacionadosHijosField;
        
        /// <remarks/>
        public string UuidConsultado {
            get {
                return this.uuidConsultadoField;
            }
            set {
                this.uuidConsultadoField = value;
            }
        }
        
        /// <remarks/>
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        public UuidPadre[] UuidsRelacionadosPadres {
            get {
                return this.uuidsRelacionadosPadresField;
            }
            set {
                this.uuidsRelacionadosPadresField = value;
            }
        }
        
        /// <remarks/>
        public UuidRelacionado[] UuidsRelacionadosHijos {
            get {
                return this.uuidsRelacionadosHijosField;
            }
            set {
                this.uuidsRelacionadosHijosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wservicios/")]
    public partial class wsConsultarCFDIRelacionadoResponse : ConsultaRelacionados {
        
        private string codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wservicios/")]
    public partial class wsConsultarEstatusCFDIResponse {
        
        private string codigoEstatusField;
        
        private string esCancelableField;
        
        private string estadoField;
        
        private string estatusCancelacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoEstatus {
            get {
                return this.codigoEstatusField;
            }
            set {
                this.codigoEstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string esCancelable {
            get {
                return this.esCancelableField;
            }
            set {
                this.esCancelableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estatusCancelacion {
            get {
                return this.estatusCancelacionField;
            }
            set {
                this.estatusCancelacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wservicios/")]
    public partial class folio {
        
        private string estatusUUIDField;
        
        private string mensajeField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estatusUUID {
            get {
                return this.estatusUUIDField;
            }
            set {
                this.estatusUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wservicios/")]
    public partial class wsCancelacionResponse {
        
        private string acuseField;
        
        private string codEstatusField;
        
        private folio[] foliosField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acuse {
            get {
                return this.acuseField;
            }
            set {
                this.acuseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codEstatus {
            get {
                return this.codEstatusField;
            }
            set {
                this.codEstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public folio[] folios {
            get {
                return this.foliosField;
            }
            set {
                this.foliosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wservicios/")]
    public partial class accesos {
        
        private string passwordField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ObjectType {
        
        private System.Xml.XmlNode[] anyField;
        
        private string idField;
        
        private string mimeTypeField;
        
        private string encodingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class RSAKeyValueType {
        
        private byte[] modulusField;
        
        private byte[] exponentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Modulus {
            get {
                return this.modulusField;
            }
            set {
                this.modulusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Exponent {
            get {
                return this.exponentField;
            }
            set {
                this.exponentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyValueType {
        
        private RSAKeyValueType[] rSAKeyValueField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RSAKeyValue")]
        public RSAKeyValueType[] RSAKeyValue {
            get {
                return this.rSAKeyValueField;
            }
            set {
                this.rSAKeyValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509IssuerSerialType {
        
        private string x509IssuerNameField;
        
        private string x509SerialNumberField;
        
        /// <remarks/>
        public string X509IssuerName {
            get {
                return this.x509IssuerNameField;
            }
            set {
                this.x509IssuerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string X509SerialNumber {
            get {
                return this.x509SerialNumberField;
            }
            set {
                this.x509SerialNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509DataType {
        
        private X509IssuerSerialType x509IssuerSerialField;
        
        private byte[] x509CertificateField;
        
        /// <remarks/>
        public X509IssuerSerialType X509IssuerSerial {
            get {
                return this.x509IssuerSerialField;
            }
            set {
                this.x509IssuerSerialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] X509Certificate {
            get {
                return this.x509CertificateField;
            }
            set {
                this.x509CertificateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyInfoType {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("KeyValue", typeof(KeyValueType))]
        [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509DataType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DigestMethodType {
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class TransformType {
        
        private string[] xPathField;
        
        private string[] textField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XPath")]
        public string[] XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ReferenceType {
        
        private TransformType[] transformsField;
        
        private DigestMethodType digestMethodField;
        
        private byte[] digestValueField;
        
        private string idField;
        
        private string uRIField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        public DigestMethodType DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureMethodType {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("HMACOutputLength", typeof(string), DataType="integer")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Cancelacion_2CompletedEventHandler(object sender, Cancelacion_2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Cancelacion_2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Cancelacion_2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsCancelacionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsCancelacionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Cancelacion_1CompletedEventHandler(object sender, Cancelacion_1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Cancelacion_1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Cancelacion_1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsCancelacionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsCancelacionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultarEstatusCFDI_1CompletedEventHandler(object sender, ConsultarEstatusCFDI_1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarEstatusCFDI_1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarEstatusCFDI_1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsConsultarEstatusCFDIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsConsultarEstatusCFDIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultarEstatusCFDI_2CompletedEventHandler(object sender, ConsultarEstatusCFDI_2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarEstatusCFDI_2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarEstatusCFDI_2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsConsultarEstatusCFDIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsConsultarEstatusCFDIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultarCFDIRelacionado_1CompletedEventHandler(object sender, ConsultarCFDIRelacionado_1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCFDIRelacionado_1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCFDIRelacionado_1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsConsultarCFDIRelacionadoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsConsultarCFDIRelacionadoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultarCFDIRelacionado_2CompletedEventHandler(object sender, ConsultarCFDIRelacionado_2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCFDIRelacionado_2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCFDIRelacionado_2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsConsultarCFDIRelacionadoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsConsultarCFDIRelacionadoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuzonPeticionesCancelacionCompletedEventHandler(object sender, BuzonPeticionesCancelacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuzonPeticionesCancelacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuzonPeticionesCancelacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsBuzonPeticionesCancelacionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsBuzonPeticionesCancelacionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AceptarRechazarSolicitudCancelacion_1CompletedEventHandler(object sender, AceptarRechazarSolicitudCancelacion_1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AceptarRechazarSolicitudCancelacion_1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AceptarRechazarSolicitudCancelacion_1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsSolicitudAceptacionRechazoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsSolicitudAceptacionRechazoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AceptarRechazarSolicitudCancelacion_2CompletedEventHandler(object sender, AceptarRechazarSolicitudCancelacion_2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AceptarRechazarSolicitudCancelacion_2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AceptarRechazarSolicitudCancelacion_2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsSolicitudAceptacionRechazoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsSolicitudAceptacionRechazoResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591